/**
 * The return gates ask about the task's surface, not about the repository.
 *
 * Three toolkit versions moved the same return-production deadlock without
 * removing it. Each fix kept the same shape of question - "did anything
 * anywhere in this repository change?" - and each was defeated by the next
 * shared path a real repository contains: generated host shims, provisioned
 * line-ending attributes, the target's own `agenticloop.json`, a lockfile. A
 * lockfile cannot be declared toolkit-owned, because it is not; and history is
 * append-only, so every such path poisons the binding permanently.
 *
 * These fixtures state the condition a real repository always satisfies: a
 * finished implementation, with unrelated shared-path commits, a toolkit
 * update, and untrailered commits around it. The task's declared
 * `allowed_paths` is the only surface either gate is entitled to ask about.
 *
 * Clean-room fixtures. Nothing here carries target repository content, session
 * text, or operator identity.
 */

import { after, before, describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { tmpdir } from 'node:os';

import { createDispatchFixture, git, prepare as prepareDispatch } from './helpers/dispatch-fixture.js';
import { protectedHostBoundary } from './helpers/host-trust-fixture.js';
import { runCliInProcess } from './helpers/run-cli.js';
import {
  evaluateReadOnlyPrepareReturnProjection,
  validateDispatchPreparation,
} from '../src/dispatch-envelope.js';

let temp;
before(() => { temp = mkdtempSync(join(tmpdir(), 'al-task-surface-')); });
after(() => { rmSync(temp, { recursive: true, force: true }); });

/** What one `Update Agentic Loop` sync rewrites; all of it manifest-declared. */
const TOOLKIT_UPDATE_PATHS = Object.freeze([
  ['agenticloop/agents/engineer.md', '# Engineer\n\nRegenerated by the toolkit updater.\n'],
  ['.claude/agents/engineer.md', '---\nname: engineer\n---\n\nGenerated shim.\n'],
]);

/**
 * Shared paths a real repository carries that the toolkit cannot own. The
 * target authors its own `agenticloop.json`, and a lockfile belongs to the
 * package manager. Neither is ever declared toolkit-owned, which is exactly
 * why a whole-repository question can never be made to pass.
 */
const SHARED_PATHS = Object.freeze([
  ['agenticloop.json', `${JSON.stringify({ documents: { rules: 'AGENTS.md' } }, null, 2)}\n`],
  ['package-lock.json', `${JSON.stringify({ name: 'target', lockfileVersion: 3 }, null, 2)}\n`],
]);

/**
 * The same shared paths as the operator's toolkit update first left them, so a
 * later refresh of the same files is a real second change rather than a no-op.
 */
const MAINTENANCE_PATHS = Object.freeze([
  ['agenticloop.json', `${JSON.stringify({ documents: { rules: 'AGENTS.md' }, generated: false }, null, 2)}\n`],
  ['package-lock.json', `${JSON.stringify({ name: 'target', lockfileVersion: 2 }, null, 2)}\n`],
]);

function carrierDigest(root, taskId = 'T-001') {
  const content = readFileSync(join(root, '.agenticloop', 'tasks', `${taskId}.md`), 'utf8');
  return `sha256:${createHash('sha256').update(content, 'utf8').digest('hex')}`;
}

function assertOk(result, label) {
  assert.equal(result.status, 0, `${label}\nstdout:\n${result.stdout}\nstderr:\n${result.stderr}`);
  return result;
}

/** Commit the named files with the given subject, exactly as written. */
function commitFiles(root, files, subject) {
  for (const [path, content] of files) {
    mkdirSync(dirname(join(root, path)), { recursive: true });
    writeFileSync(join(root, path), content, 'utf8');
  }
  git(root, ['add', ...files.map(([path]) => path)]);
  git(root, ['commit', '-m', subject]);
  return git(root, ['rev-parse', 'HEAD']);
}

/**
 * A task whose implementation is finished, in a repository that also moved
 * around it:
 *
 *   base -> role start -> untrailered toolkit update -> implementation
 *        -> untrailered shared-path commit
 *
 * The toolkit update sits inside the return range and carries no canonical
 * trailers - the operator ran the updater, not the loop. The shared-path commit
 * lands after the implementation and touches nothing this task declared.
 */
async function implementedTask(name, {
  maintenancePaths = [],
  attemptAuthoredOffSurface = null,
  offSurfaceTrailered = true,
} = {}) {
  const fixture = await createDispatchFixture(temp, name, {
    requiredChecksText: '- [RC-1] command: `node --version`\n- [RC-2] command: `node --version`',
  });
  const root = fixture.root;
  const cli = args => runCliInProcess([...args, '--target', root], {
    operatorTrustRoot: fixture.operatorTrustRoot,
    hostAuthority: protectedHostBoundary(fixture.trust),
  });
  mkdirSync(join(root, '.agenticloop', 'tmp'), { recursive: true });

  const packetPath = '.agenticloop/tmp/packet.json';
  writeFileSync(join(root, packetPath), JSON.stringify(prepareDispatch(fixture).packet), 'utf8');
  assertOk(await cli([
    'task', 'status', 'T-001', 'in-progress',
    '--expect-digest', carrierDigest(root), '--dispatch-packet', packetPath, '--json',
  ]), 'role start');

  // Inside the return range, and untrailered: the toolkit updater is not the
  // loop and does not write canonical Task:/Agent: trailers.
  const toolkitUpdate = commitFiles(root, [...TOOLKIT_UPDATE_PATHS, ...maintenancePaths], 'Update Agentic Loop');

  // An off-surface edit the attempt itself authored. It carries the loop's own
  // canonical trailers, so no ownership question arises: it is this task's work,
  // and task work outside `allowed_paths` is what the scope gate exists for.
  const offSurfaceHead = attemptAuthoredOffSurface
    ? commitFiles(root, [attemptAuthoredOffSurface], offSurfaceTrailered
      ? 'touch a path this task never declared\n\nTask: T-001\nAgent: engineer'
      // No trailers at all. An attempt that simply declines to declare its own
      // commit must not thereby place it beyond the scope gate.
      : 'touch a path this task never declared')
    : null;

  writeFileSync(join(root, 'src', 'existing.js'), 'export const current = "implemented";\n', 'utf8');
  git(root, ['add', 'src/existing.js']);
  git(root, ['commit', '-m', 'implement the task\n\nTask: T-001\nAgent: engineer']);
  const productHead = git(root, ['rev-parse', 'HEAD']);

  const sharedHead = commitFiles(root, SHARED_PATHS, 'chore: refresh target config and lockfile');

  return { fixture, root, cli, packetPath, toolkitUpdate, offSurfaceHead, productHead, sharedHead };
}

/**
 * Bind the implementation, execute the required checks, and produce the raw
 * return. Every return fixture needs this same chain; only the history around
 * it differs.
 */
async function produceReturn({ root, cli, packetPath }, productHead, slug) {
  assertOk(await cli([
    'task', 'evidence', 'T-001', '--class', 'implementation_artifact_evidence',
    '--expect-digest', carrierDigest(root), '--product-head', productHead, '--json',
  ]), 'implementation artifact evidence');

  const checksPath = `.agenticloop/tmp/${slug}-checks.json`;
  assertOk(await cli([
    'task', 'check-evidence-init', 'T-001', '--packet', packetPath, '--output', checksPath, '--json',
  ]), 'check evidence init');
  for (const check of JSON.parse(readFileSync(join(root, checksPath), 'utf8'))) {
    assertOk(await cli([
      'task', 'check-evidence-update', 'T-001', '--packet', packetPath,
      '--input', checksPath, '--output', checksPath, '--check', check.id,
      '--outcome', 'passed', '--evidence', `${check.id} passed`, '--json',
    ]), `check evidence update ${check.id}`);
  }

  const returnPath = `.agenticloop/tmp/${slug}-return.json`;
  const prepared = await cli([
    'task', 'prepare-return', 'T-001', '--packet', packetPath, '--check-evidence', checksPath,
    '--outcome', 'implementation_ready_for_review', '--output', returnPath, '--json',
  ]);
  return { returnPath, prepared };
}

describe('return gates are scoped to the task surface', () => {
  it('keeps an authenticated full prepare-return path distinct from read-only unknown inputs', async () => {
    const { fixture, root, cli, packetPath, productHead } = await implementedTask('full-return-vs-read-only');
    const packet = JSON.parse(readFileSync(join(root, packetPath), 'utf8'));

    // The exact Auditor mismatch probe: the genuine packet validates with the
    // protected caller's capability/resolver context, but not with read-only
    // defaults that have no authenticated capability inventory.
    assert.equal(validateDispatchPreparation(packet, fixture.options).ok, true);
    assert.equal(validateDispatchPreparation(packet).ok, false);

    assertOk(await cli([
      'task', 'evidence', 'T-001', '--class', 'implementation_artifact_evidence',
      '--expect-digest', carrierDigest(root), '--product-head', productHead, '--json',
    ]), 'implementation artifact evidence');
    const checksPath = '.agenticloop/tmp/full-return-checks.json';
    assertOk(await cli([
      'task', 'check-evidence-init', 'T-001', '--packet', packetPath, '--output', checksPath, '--json',
    ]), 'check evidence init');
    for (const check of JSON.parse(readFileSync(join(root, checksPath), 'utf8'))) {
      assertOk(await cli([
        'task', 'check-evidence-update', 'T-001', '--packet', packetPath,
        '--input', checksPath, '--output', checksPath, '--check', check.id,
        '--outcome', 'passed', '--evidence', `${check.id} passed`, '--json',
      ]), `check evidence update ${check.id}`);
    }
    assertOk(await cli([
      'task', 'prepare-return', 'T-001', '--packet', packetPath, '--check-evidence', checksPath,
      '--outcome', 'implementation_ready_for_review', '--output', '.agenticloop/tmp/full-return.json', '--json',
    ]), 'fully provisioned protected prepare-return');

    // Explain cannot receive caller-only authenticated options, selected
    // aggregate, and output/candidate authority. It must remain canonical
    // unknown rather than contradicting the successful protected path with a
    // false legal (or a false refusal).
    const projection = evaluateReadOnlyPrepareReturnProjection({
      target: root, taskId: 'T-001',
      projectConfig: { task_file_template: '.agenticloop/tasks/{taskId}.md' },
      packet,
    });
    assert.equal(projection.verdict, 'unknown');
    assert.notEqual(projection.verdict, 'legal');
    assert.ok(projection.reasons.some(reason =>
      reason.fact === 'required_check_evidence.current' && reason.state === 'unknown'));
  });

  it('binds the implementation with unrelated shared paths changed after it', async () => {
    const { root, cli, productHead, sharedHead } = await implementedTask('bind-past-shared-paths');
    assert.notEqual(sharedHead, productHead, 'HEAD is past the implementation, exactly as in the field');

    assertOk(await cli([
      'task', 'evidence', 'T-001', '--class', 'implementation_artifact_evidence',
      '--expect-digest', carrierDigest(root), '--product-head', productHead, '--json',
    ]), 'implementation artifact evidence with shared paths changed after the implementation');
    assert.match(
      readFileSync(join(root, '.agenticloop', 'tasks', 'T-001.md'), 'utf8'),
      new RegExp(`implementation_artifact: commit:${productHead}`),
      'the record names the implementation, not a later shared-path commit'
    );
  });

  it('still refuses a commit that touches nothing this task declared', async () => {
    const { root, cli, sharedHead } = await implementedTask('refuse-off-surface-head');

    const refused = await cli([
      'task', 'evidence', 'T-001', '--class', 'implementation_artifact_evidence',
      '--expect-digest', carrierDigest(root), '--product-head', sharedHead, '--json',
    ]);
    assert.equal(refused.status, 1, 'a commit outside the task surface is not an implementation');
    assert.match(JSON.parse(refused.stdout).errors.join('\n'), /allowed_paths/);
  });

  it('accepts re-affirming the binding the record already carries', async () => {
    const { root, cli, productHead } = await implementedTask('reaffirm-binding');
    assertOk(await cli([
      'task', 'evidence', 'T-001', '--class', 'implementation_artifact_evidence',
      '--expect-digest', carrierDigest(root), '--product-head', productHead, '--json',
    ]), 'first binding');

    const again = await cli([
      'task', 'evidence', 'T-001', '--class', 'implementation_artifact_evidence',
      '--expect-digest', carrierDigest(root), '--product-head', productHead, '--json',
    ]);
    assertOk(again, 're-affirming the current binding');
    assert.equal(JSON.parse(again.stdout).bindingAlreadyCurrent, true);
  });

  it('produces and verifies a return over a range holding an untrailered commit', async () => {
    const { root, cli, packetPath, productHead, toolkitUpdate } = await implementedTask('return-over-untrailered');
    assert.notEqual(toolkitUpdate, productHead);

    assertOk(await cli([
      'task', 'evidence', 'T-001', '--class', 'implementation_artifact_evidence',
      '--expect-digest', carrierDigest(root), '--product-head', productHead, '--json',
    ]), 'implementation artifact evidence');

    // The operator syncs the toolkit mid-attempt, inside this attempt's own
    // region. That rewrites the generator's output manifest and the project
    // map: toolkit-written target state, neither of which is one of the loop's
    // records.
    writeFileSync(
      join(root, '.agenticloop', 'generated-artifacts.json'),
      JSON.stringify({ schemaVersion: 4, packageVersion: '0.0.0-test', entries: [] }, null, 2),
      'utf8'
    );
    writeFileSync(join(root, '.agenticloop', 'project.md'), '---\ntask_backend: files\n---\n\n# Project\n', 'utf8');
    git(root, ['add', '.agenticloop/generated-artifacts.json', '.agenticloop/project.md']);
    git(root, ['commit', '-m', 'Update Agentic Loop']);

    const checksPath = '.agenticloop/tmp/checks.json';
    assertOk(await cli([
      'task', 'check-evidence-init', 'T-001', '--packet', packetPath, '--output', checksPath, '--json',
    ]), 'check evidence init');
    for (const check of JSON.parse(readFileSync(join(root, checksPath), 'utf8'))) {
      assertOk(await cli([
        'task', 'check-evidence-update', 'T-001', '--packet', packetPath,
        '--input', checksPath, '--output', checksPath, '--check', check.id,
        '--outcome', 'passed', '--evidence', `${check.id} passed`, '--json',
      ]), `check evidence update ${check.id}`);
    }

    const returnPath = '.agenticloop/tmp/return.json';
    assertOk(await cli([
      'task', 'prepare-return', 'T-001', '--packet', packetPath, '--check-evidence', checksPath,
      '--outcome', 'implementation_ready_for_review', '--output', returnPath, '--json',
    ]), 'prepare-return over a range holding an untrailered toolkit-update commit');

    const roleReturn = JSON.parse(readFileSync(join(root, returnPath), 'utf8'));
    assert.equal(roleReturn.productHead, productHead);
    assert.deepEqual(roleReturn.productChangedPaths, ['src/existing.js'],
      'only the task surface is attributed to the product');
    assert.ok(roleReturn.productAttribution.commits.includes(toolkitUpdate),
      'the untrailered commit stays in the durable range; it is simply not attributed work');
    for (const path of ['.agenticloop/generated-artifacts.json', '.agenticloop/project.md']) {
      assert.ok(roleReturn.workflowChangedPaths.includes(path),
        `toolkit-written target state is workflow state, not an unknown path: ${path}`);
    }

    assertOk(await cli([
      'task', 'verify-return', 'T-001', '--packet', packetPath, '--return', returnPath,
      '--from-current-repository', '--json',
    ]), 'verify-return over a range holding an untrailered toolkit-update commit');

    assertOk(await cli(['task', 'review-prepare', 'T-001', '--json']), 'review entry from the verified return');

    // The protected check update commits its own execution artifacts. Every
    // later refetch therefore reads that history without a role-authored
    // bookkeeping commit or an unknown-path classification.
    const afterCommit = await cli(['task', 'review-prepare', 'T-001', '--json']);
    assert.doesNotMatch(
      `${afterCommit.stdout}${afterCommit.stderr}`,
      /unknown workflow path/,
      'committed check proof is workflow evidence, not an unknown path'
    );
  });

  /**
   * The fourth field cohort's blocker, and the escape its first repair opened.
   *
   * A range that begins at this attempt's own base contains only this attempt's
   * span, so every untrailered commit in it landed while the attempt was live.
   * Nothing in the records distinguishes such a commit from one the attempt
   * authored and declined to declare - there is no per-commit product receipt -
   * so it is undecidable, and undecidable resolves toward the task.
   *
   * Separately-owned maintenance from *before* the attempt is the case the
   * field actually hit, and it can only be expressed with carried lineage.
   * That proof lives in test/resumed-attempt-return.test.js, where a carried
   * base reaches back across an abandoned attempt exactly as the cohort's did.
   */
  it('refuses an undeclared product-path commit made while the attempt was live', async () => {
    const context = await implementedTask('undeclared-in-window', { maintenancePaths: MAINTENANCE_PATHS });
    const { root, cli, packetPath, productHead } = context;
    const { returnPath, prepared } = await produceReturn(context, productHead, 'undeclared');
    assertOk(prepared, 'prepare-return still produces the return; the scope gate is the refusal');

    const roleReturn = JSON.parse(readFileSync(join(root, returnPath), 'utf8'));
    // The repair changes what is refused, not what is reported.
    for (const [path] of MAINTENANCE_PATHS) {
      assert.ok(roleReturn.productChangedPaths.includes(path),
        `the range inventory still reports '${path}'`);
    }

    const refused = await cli([
      'task', 'verify-return', 'T-001', '--packet', packetPath, '--return', returnPath,
      '--from-current-repository', '--json',
    ]);
    assert.equal(refused.status, 1,
      `an undeclared in-window product path is refused\n${refused.stdout}${refused.stderr}`);
    assert.match(`${refused.stdout}${refused.stderr}`, /is outside packet-bound task scope/);
  });

  it('still refuses an out-of-scope path the attempt itself authored', async () => {
    const context = await implementedTask('attempt-authored-off-surface', {
      attemptAuthoredOffSurface: ['off-surface.md', '# Not this task\n'],
    });
    const { root, cli, packetPath, productHead, offSurfaceHead } = context;
    assert.notEqual(offSurfaceHead, productHead, 'the off-surface commit sits inside the return range');

    const { returnPath, prepared } = await produceReturn(context, productHead, 'off-surface');
    assertOk(prepared, 'prepare-return still produces the return; the scope gate is the refusal');

    const refused = await cli([
      'task', 'verify-return', 'T-001', '--packet', packetPath, '--return', returnPath,
      '--from-current-repository', '--json',
    ]);
    assert.equal(refused.status, 1, `an attempt-authored out-of-scope path is still refused\n${refused.stdout}${refused.stderr}`);
    assert.match(
      `${refused.stdout}${refused.stderr}`,
      /product changed path 'off-surface\.md' is outside packet-bound task scope/,
      'the refusal names the path the attempt authored'
    );
  });

  /**
   * The escape the trailer-only ownership rule opened: a trailer is a voluntary
   * declaration, so reading its absence as "not this task's work" let an
   * attempt put an out-of-scope edit beyond every gate by simply not declaring
   * it. Identical to the case above in every respect except the trailers.
   */
  it('refuses an out-of-scope path the attempt authored without declaring it', async () => {
    const context = await implementedTask('attempt-authored-undeclared', {
      attemptAuthoredOffSurface: ['off-surface.md', '# Not this task\n'],
      offSurfaceTrailered: false,
    });
    const { root, cli, packetPath, productHead } = context;
    const { returnPath, prepared } = await produceReturn(context, productHead, 'undeclared-off-surface');
    assertOk(prepared, 'prepare-return still produces the return; the scope gate is the refusal');

    const refused = await cli([
      'task', 'verify-return', 'T-001', '--packet', packetPath, '--return', returnPath,
      '--from-current-repository', '--json',
    ]);
    assert.equal(refused.status, 1,
      `omitting the trailers must not place the edit beyond the gate\n${refused.stdout}${refused.stderr}`);
    assert.match(
      `${refused.stdout}${refused.stderr}`,
      /product changed path 'off-surface\.md' is outside packet-bound task scope/,
      'the undeclared path is named exactly as the declared one is'
    );
  });
});
