/**
 * The toolkit's own output is not the product's work.
 *
 * Agentic Loop writes files into the target it manages: installed toolkit
 * source under `agenticloop/`, generated host shims under `.opencode/`,
 * `.claude/`, `.codex/` and their siblings, and the line-ending attributes that
 * keep committed identity portable. `manifest.json` has always declared all of
 * them. Product lineage did not read that declaration - it tested one path
 * prefix, `.agenticloop` - so every one of those files counted as product work.
 *
 * The consequence is a constraint set no repository state can satisfy. Run the
 * toolkit updater after the implementation lands and the implementation commit
 * stops being "the last commit carrying product work"; the update commit that
 * follows introduces no product path, so it is not an implementation artifact
 * either. `task evidence` then refuses every candidate `--product-head`, and
 * `prepare-return` refuses on the consequence.
 *
 * These fixtures reproduce that from a clean-room repository: a real
 * implementation commit, then commits touching only paths the toolkit itself
 * writes. Nothing here is specific to any target project.
 */

import { after, before, describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { tmpdir } from 'node:os';

import { createDispatchFixture, prepare as prepareDispatch } from './helpers/dispatch-fixture.js';
import { protectedHostBoundary } from './helpers/host-trust-fixture.js';
import { runCliInProcess } from './helpers/run-cli.js';

let temp;
before(() => { temp = mkdtempSync(join(tmpdir(), 'al-toolkit-lineage-')); });
after(() => { rmSync(temp, { recursive: true, force: true }); });

/**
 * Exactly what one `Update Agentic Loop` sync rewrites in a target: installed
 * toolkit source, one generated host shim, and the provisioned line-ending
 * attributes. Every one of them is declared in `manifest.json`.
 */
const TOOLKIT_UPDATE_PATHS = Object.freeze([
  ['agenticloop/agents/engineer.md', '# Engineer\n\nRegenerated by the toolkit updater.\n'],
  ['.opencode/agent/engineer.md', '---\nname: engineer\n---\n\nGenerated shim.\n'],
  ['.claude/agents/engineer.md', '---\nname: engineer\n---\n\nGenerated shim.\n'],
  ['.gitattributes', '*.md text eol=lf\n*.json text eol=lf\n'],
]);

function git(cwd, args) {
  const result = spawnSync('git', ['-C', cwd, ...args], { encoding: 'utf-8' });
  assert.equal(result.status, 0, `git ${args.join(' ')}\n${result.stdout}\n${result.stderr}`);
  return result.stdout.trim();
}

function carrierDigest(root, taskId = 'T-001') {
  const content = readFileSync(join(root, '.agenticloop', 'tasks', `${taskId}.md`), 'utf8');
  return `sha256:${createHash('sha256').update(content, 'utf8').digest('hex')}`;
}

function assertOk(result, label) {
  assert.equal(result.status, 0, `${label}\nstdout:\n${result.stdout}\nstderr:\n${result.stderr}`);
  return result;
}

/** Write and commit one toolkit-update sync, exactly as the updater would. */
function commitToolkitUpdate(root, subject) {
  for (const [path, content] of TOOLKIT_UPDATE_PATHS) {
    mkdirSync(dirname(join(root, path)), { recursive: true });
    // Each sync rewrites the same paths with new bytes, so repeated updates are
    // genuinely distinct commits rather than empty ones.
    writeFileSync(join(root, path), `${content}<!-- ${subject} -->\n`, 'utf8');
  }
  git(root, ['add', ...TOOLKIT_UPDATE_PATHS.map(([path]) => path)]);
  git(root, ['commit', '-m', subject]);
  return git(root, ['rev-parse', 'HEAD']);
}

async function implementedTask(name) {
  const fixture = await createDispatchFixture(temp, name, {
    requiredChecksText: '- [RC-1] command: `node --version`\n- [RC-2] command: `node --version`',
  });
  const root = fixture.root;
  const cli = args => runCliInProcess([...args, '--target', root], {
    operatorTrustRoot: fixture.operatorTrustRoot,
    hostAuthority: protectedHostBoundary(fixture.trust),
  });
  mkdirSync(join(root, '.agenticloop', 'tmp'), { recursive: true });

  const packetPath = '.agenticloop/tmp/packet.json';
  writeFileSync(join(root, packetPath), JSON.stringify(prepareDispatch(fixture).packet), 'utf8');
  assertOk(await cli([
    'task', 'status', 'T-001', 'in-progress',
    '--expect-digest', carrierDigest(root), '--dispatch-packet', packetPath, '--json',
  ]), 'role start');

  writeFileSync(join(root, 'src', 'existing.js'), 'export const current = "implemented";\n', 'utf8');
  git(root, ['add', 'src/existing.js']);
  git(root, ['commit', '-m', 'implement the task\n\nTask: T-001\nAgent: engineer']);

  return { fixture, root, cli, packetPath, productHead: git(root, ['rev-parse', 'HEAD']) };
}

describe('a toolkit update does not invalidate the implementation artifact', () => {
  it('binds the implementation after any number of toolkit-generated commits', async () => {
    const { root, cli, productHead } = await implementedTask('after-update');

    // Three syncs, exactly the shape the field run met: the implementation is
    // buried under toolkit output and nothing else.
    commitToolkitUpdate(root, 'update Agentic Loop');
    commitToolkitUpdate(root, 'update Agentic Loop again');
    const head = commitToolkitUpdate(root, 'update Agentic Loop once more');
    assert.notEqual(head, productHead, 'HEAD is past the implementation, exactly as in the field');

    const bound = await cli([
      'task', 'evidence', 'T-001', '--class', 'implementation_artifact_evidence',
      '--expect-digest', carrierDigest(root), '--product-head', productHead, '--json',
    ]);
    assertOk(bound, 'implementation artifact evidence after toolkit updates');
    assert.match(
      readFileSync(join(root, '.agenticloop', 'tasks', 'T-001.md'), 'utf8'),
      new RegExp(`implementation_artifact: commit:${productHead}`),
      'the record names the implementation, not a toolkit-update commit'
    );
  });

  it('still refuses a toolkit-update commit as the implementation artifact', async () => {
    const { root, cli } = await implementedTask('update-only-head');
    const updateHead = commitToolkitUpdate(root, 'update Agentic Loop');

    const refused = await cli([
      'task', 'evidence', 'T-001', '--class', 'implementation_artifact_evidence',
      '--expect-digest', carrierDigest(root), '--product-head', updateHead, '--json',
    ]);
    assert.equal(refused.status, 1, 'a commit carrying only toolkit output is not an implementation');
    // The guard is unchanged; the question it asks is narrower. A toolkit-update
    // commit is refused because it touches nothing the task declared, not because
    // a repository-wide classifier calls its paths workflow output.
    assert.match(
      JSON.parse(refused.stdout).errors.join('\n'),
      /changes at least one path this task declares in allowed_paths/
    );
  });

  it('reaches a verified return with the implementation buried under toolkit output', async () => {
    const { root, cli, packetPath, productHead } = await implementedTask('return-after-update');
    commitToolkitUpdate(root, 'update Agentic Loop');

    assertOk(await cli([
      'task', 'evidence', 'T-001', '--class', 'implementation_artifact_evidence',
      '--expect-digest', carrierDigest(root), '--product-head', productHead, '--json',
    ]), 'implementation artifact evidence');

    const checksPath = '.agenticloop/tmp/checks.json';
    assertOk(await cli([
      'task', 'check-evidence-init', 'T-001', '--packet', packetPath, '--output', checksPath, '--json',
    ]), 'check evidence init');
    for (const check of JSON.parse(readFileSync(join(root, checksPath), 'utf8'))) {
      assertOk(await cli([
        'task', 'check-evidence-update', 'T-001', '--packet', packetPath,
        '--input', checksPath, '--output', checksPath, '--check', check.id,
        '--outcome', 'passed', '--evidence', `${check.id} passed`, '--json',
      ]), `check evidence update ${check.id}`);
      // No `--execution-output`: the artifact lands on a tracked path, so the
      // proof a reviewer is pointed at survives the checkout that produced it.
      assert.ok(
        existsSync(join(root, '.agenticloop', 'checks', 'T-001', `${check.id}.execution.json`)),
        `execution evidence for ${check.id} must land on a tracked path`
      );
    }

    const returnPath = '.agenticloop/tmp/return.json';
    assertOk(await cli([
      'task', 'prepare-return', 'T-001', '--packet', packetPath, '--check-evidence', checksPath,
      '--outcome', 'implementation_ready_for_review', '--output', returnPath, '--json',
    ]), 'prepare-return with the implementation behind toolkit output');

    const roleReturn = JSON.parse(readFileSync(join(root, returnPath), 'utf8'));
    assert.equal(roleReturn.productHead, productHead);
    assert.deepEqual(roleReturn.productChangedPaths, ['src/existing.js'],
      'toolkit output is not attributed to the product');

    assertOk(await cli([
      'task', 'verify-return', 'T-001', '--packet', packetPath, '--return', returnPath,
      '--from-current-repository', '--json',
    ]), 'verify-return with the implementation behind toolkit output');
  });
});
