import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';

import { digest, readManifest } from '../src/generated.js';
import { CONFIG_FILE, GENERATED_MANIFEST, PROJECT_FILE, TASKS_DIRECTORY } from '../src/layout.js';
import { doctor, remove, setup, update } from '../src/setup.js';
import { validate } from '../src/validate.js';

/** Each fixture is its own temp tree, removed when the test ends. */
function fixture(t) {
  const root = fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(), 'castwork-test-')));
  t.after(() => fs.rmSync(root, { recursive: true, force: true }));
  return root;
}

test('setup creates the state directories and records what it generated', (t) => {
  const root = fixture(t);
  const result = setup(root, { hosts: ['codex'] });
  assert.ok(fs.existsSync(path.join(root, PROJECT_FILE)));
  assert.ok(fs.existsSync(path.join(root, TASKS_DIRECTORY)));
  assert.ok(fs.existsSync(path.join(root, GENERATED_MANIFEST)));
  assert.ok(result.added.length > 0);
  const manifest = readManifest(root);
  assert.equal(Object.keys(manifest.files).length, result.added.length);
});

test('setup adds the local directory to .gitignore', (t) => {
  const root = fixture(t);
  setup(root, { hosts: ['codex'] });
  assert.match(fs.readFileSync(path.join(root, '.gitignore'), 'utf8'), /\.castwork\/local\//);
});

test('setup refuses without a host rather than guessing', (t) => {
  const root = fixture(t);
  assert.throws(() => setup(root, { hosts: [] }), /no hosts selected/);
});

/**
 * Make one generated file stale the way a toolkit change does: the file and its
 * manifest digest agree, but neither matches what would be generated now.
 */
function makeStale(root, relative) {
  fs.writeFileSync(path.join(root, relative), 'generated by an older toolkit\n', 'utf8');
  const manifestFile = path.join(root, GENERATED_MANIFEST);
  const manifest = JSON.parse(fs.readFileSync(manifestFile, 'utf8'));
  manifest.files[relative] = digest('generated by an older toolkit\n');
  fs.writeFileSync(manifestFile, `${JSON.stringify(manifest, null, 2)}\n`, 'utf8');
}

/** Every file under root, with its content, for proving nothing was written. */
function snapshot(root) {
  /** @type {Record<string, string>} */
  const files = {};
  for (const entry of fs.readdirSync(root, { recursive: true, withFileTypes: true })) {
    if (!entry.isFile()) continue;
    const full = path.join(entry.parentPath, entry.name);
    files[path.relative(root, full)] = fs.readFileSync(full, 'utf8');
  }
  return files;
}

test('update refuses as a whole when a generated file was modified, and applies when it is forced', (t) => {
  const root = fixture(t);
  const result = setup(root, { hosts: ['codex'] });
  const [target, stale] = result.added;
  makeStale(root, stale);
  fs.writeFileSync(path.join(root, target), 'edited by hand\n', 'utf8');
  const before = snapshot(root);

  assert.throws(() => update(root), (error) => /nothing was written/.test(error.message) && error.message.includes(target));
  assert.deepEqual(snapshot(root), before, 'a refused update writes nothing, not even the stale file it could have fixed');

  const forced = update(root, { force: [target] });
  assert.deepEqual(forced.changed.sort(), [target, stale].sort());
  assert.notEqual(fs.readFileSync(path.join(root, target), 'utf8'), 'edited by hand\n');
});

test('a file of yours at a generated path refuses setup, and is replaced only when named', (t) => {
  const root = fixture(t);
  const planned = setup(root, { hosts: ['codex'] });
  const target = planned.added[0];
  remove(root);

  fs.mkdirSync(path.dirname(path.join(root, target)), { recursive: true });
  fs.writeFileSync(path.join(root, target), 'mine\n', 'utf8');

  assert.throws(() => setup(root, { hosts: ['codex'] }), (error) => error.message.includes(`${target} (yours`));
  assert.equal(fs.readFileSync(path.join(root, target), 'utf8'), 'mine\n');
  assert.ok(!fs.existsSync(path.join(root, GENERATED_MANIFEST)), 'a refused setup writes no manifest');

  const forced = setup(root, { hosts: ['codex'], force: [target] });
  assert.ok(forced.changed.includes(target));
  assert.notEqual(fs.readFileSync(path.join(root, target), 'utf8'), 'mine\n');
});

test('a file that already holds what would be generated is adopted, not refused', (t) => {
  const root = fixture(t);
  setup(root, { hosts: ['codex'] });
  fs.rmSync(path.join(root, GENERATED_MANIFEST));

  const result = update(root);
  assert.deepEqual(result.added, []);
  assert.deepEqual(result.changed, []);
  assert.ok(result.unchanged.length > 0);
  assert.equal(result.manifest, 'added', 'writing the manifest is reported, since it has to be committed');
  assert.ok(fs.existsSync(path.join(root, GENERATED_MANIFEST)));
});

test('update reports the manifest whenever it rewrites it', (t) => {
  const root = fixture(t);
  const result = setup(root, { hosts: ['codex'] });
  assert.equal(result.manifest, 'added');

  makeStale(root, result.added[0]);
  assert.equal(update(root).manifest, 'changed');
  assert.equal(update(root).manifest, null);
});

test('a write that fails partway leaves files a second update finishes', (t) => {
  const root = fixture(t);
  const result = setup(root, { hosts: ['codex'] });
  const [first, second] = result.added;
  makeStale(root, first);
  makeStale(root, second);

  const original = fs.writeFileSync;
  let calls = 0;
  fs.writeFileSync = (...args) => {
    calls += 1;
    if (calls === 2) throw new Error('disk full');
    return original(...args);
  };
  try {
    assert.throws(() => update(root), /disk full/);
  } finally {
    fs.writeFileSync = original;
  }
  assert.notEqual(fs.readFileSync(path.join(root, first), 'utf8'), 'generated by an older toolkit\n', 'precondition: the first write landed');
  assert.equal(fs.readFileSync(path.join(root, second), 'utf8'), 'generated by an older toolkit\n', 'precondition: the second did not');

  const again = update(root);
  assert.deepEqual(again.changed, [second]);
  assert.ok(again.unchanged.includes(first), 'the file written before the failure is adopted, not refused');
  assert.equal(update(root, { check: true }).plan.current, true);
});

test('--force-generated accepts any spelling of a generated path', (t) => {
  const root = fixture(t);
  const result = setup(root, { hosts: ['codex'] });
  const target = result.added[0];
  fs.writeFileSync(path.join(root, target), 'edited by hand\n', 'utf8');

  const forced = update(root, { force: [`./${target.replace(/\//g, '\\')}`] });
  assert.deepEqual(forced.changed, [target]);
});

test('--force-generated naming no generated path is refused before anything is written', (t) => {
  const root = fixture(t);
  const result = setup(root, { hosts: ['codex'] });
  makeStale(root, result.added[0]);
  const before = snapshot(root);

  assert.throws(() => update(root, { force: ['nope.md'] }), /neither generates nor recorded: nope\.md/);
  assert.throws(() => update(root, { force: ['nope.md'], check: true }), /nope\.md/);
  assert.deepEqual(snapshot(root), before);
});

test('update --check lists what would change and writes nothing', (t) => {
  const root = fixture(t);
  const result = setup(root, { hosts: ['codex'] });
  assert.equal(update(root, { check: true }).plan.current, true);

  const stale = result.added[0];
  makeStale(root, stale);
  const before = snapshot(root);
  const { plan } = update(root, { check: true });
  assert.deepEqual(plan.changed, [stale]);
  assert.equal(plan.current, false);
  assert.equal(plan.blocked, false);
  assert.equal(plan.files, undefined, 'the public plan carries no contents');
  assert.deepEqual(snapshot(root), before);
});

test('update with nothing to do writes nothing', (t) => {
  const root = fixture(t);
  setup(root, { hosts: ['codex'] });
  const manifest = path.join(root, GENERATED_MANIFEST);
  const earlier = new Date(Math.floor(Date.now() / 1000) * 1000 - 60_000);
  fs.utimesSync(manifest, earlier, earlier);

  const result = update(root);
  assert.deepEqual([...result.added, ...result.changed, ...result.removed], []);
  assert.equal(fs.statSync(manifest).mtimeMs, earlier.getTime(), 'the manifest is not rewritten');
});

test('update reports only the files whose content changed', (t) => {
  const root = fixture(t);
  const result = setup(root, { hosts: ['codex'] });
  const stale = result.added[1];
  makeStale(root, stale);
  const updated = update(root);
  assert.deepEqual(updated.changed, [stale]);
  assert.deepEqual(updated.added, []);
});

test('remove deletes generated files and never touches records', (t) => {
  const root = fixture(t);
  setup(root, { hosts: ['codex'] });
  fs.writeFileSync(path.join(root, TASKS_DIRECTORY, 'T-001.md'), '---\nschema: 1\nid: T-001\ntitle: t\nstatus: draft\n---\n', 'utf8');

  const result = remove(root);
  assert.ok(result.removed.length > 0);
  assert.ok(fs.existsSync(path.join(root, TASKS_DIRECTORY, 'T-001.md')));
  assert.ok(fs.existsSync(path.join(root, PROJECT_FILE)));
  assert.ok(!fs.existsSync(path.join(root, GENERATED_MANIFEST)));
});

test('remove keeps a generated file the user modified', (t) => {
  const root = fixture(t);
  const result = setup(root, { hosts: ['codex'] });
  const target = result.added[0];
  fs.writeFileSync(path.join(root, target), 'edited\n', 'utf8');

  const removed = remove(root);
  assert.ok(removed.kept.includes(target));
  assert.ok(fs.existsSync(path.join(root, target)));
});

test('doctor reports a healthy installation and a missing one', (t) => {
  const root = fixture(t);
  const before = doctor(root);
  assert.equal(before.ok, false);

  setup(root, { hosts: ['codex', 'opencode'] });
  const after = doctor(root);
  assert.equal(after.ok, true);
  assert.deepEqual(after.hosts, ['codex', 'opencode']);
  assert.ok(after.generated_files > 0);
});

test('doctor notices a locally modified generated file without failing', (t) => {
  const root = fixture(t);
  const result = setup(root, { hosts: ['codex'] });
  fs.writeFileSync(path.join(root, result.added[0]), 'edited\n', 'utf8');
  const report = doctor(root);
  assert.equal(report.ok, true);
  assert.equal(report.generated, 'blocked');
  assert.ok(report.findings.some((finding) => finding.message.includes('modified locally')));
});

test('doctor says whether the generated files are current for the toolkit it ran', (t) => {
  const root = fixture(t);
  const result = setup(root, { hosts: ['codex'] });
  assert.equal(doctor(root).generated, 'current');

  makeStale(root, result.added[0]);
  const report = doctor(root);
  assert.equal(report.ok, true, 'being behind is worth fixing, not an error');
  assert.equal(report.generated, 'behind');
  assert.ok(report.findings.some((finding) => /1 generated file\(s\) differ/.test(finding.message)));
});

test('doctor reports a manifest that no longer matches, even when every file does', (t) => {
  const root = fixture(t);
  const result = setup(root, { hosts: ['codex'] });
  const manifestFile = path.join(root, GENERATED_MANIFEST);
  const manifest = JSON.parse(fs.readFileSync(manifestFile, 'utf8'));
  delete manifest.files[result.added[0]];
  fs.writeFileSync(manifestFile, JSON.stringify(manifest), 'utf8');

  const report = doctor(root);
  assert.equal(report.generated, 'behind');
  assert.ok(report.findings.some((finding) => finding.message.includes('does not match the generated files')));
});

test('doctor points a lost manifest at update, which rebuilds it', (t) => {
  const root = fixture(t);
  setup(root, { hosts: ['codex'] });
  fs.rmSync(path.join(root, GENERATED_MANIFEST));

  const report = doctor(root);
  assert.equal(report.generated, 'behind');
  assert.ok(report.findings.some((finding) => finding.message.includes('is missing') && finding.next === 'Run update.'));
});

test('setup is idempotent', (t) => {
  const root = fixture(t);
  const first = setup(root, { hosts: ['claude'] });
  const second = setup(root, { hosts: ['claude'] });
  assert.deepEqual(second.unchanged.sort(), first.added.sort());
  assert.deepEqual([...second.added, ...second.changed, ...second.removed], []);
});

test('naming a host adds it and leaves the other hosts files in place', (t) => {
  const root = fixture(t);
  const first = setup(root, { hosts: ['codex'] });
  const second = setup(root, { hosts: ['claude'] });

  assert.deepEqual(second.hosts, ['codex', 'claude']);
  assert.deepEqual(second.added_hosts, ['claude']);
  assert.deepEqual(second.removed, []);
  for (const relative of first.added) {
    assert.ok(fs.existsSync(path.join(root, relative)), `${relative} was deleted by adding a host`);
  }
  assert.ok(second.added.some((relative) => relative.startsWith('.claude/')));
  assert.deepEqual(JSON.parse(fs.readFileSync(path.join(root, CONFIG_FILE), 'utf8')).hosts, ['codex', 'claude']);
});

test('naming a host that is already recorded adds nothing', (t) => {
  const root = fixture(t);
  setup(root, { hosts: ['codex'] });
  const again = setup(root, { hosts: ['codex'] });
  assert.deepEqual(again.hosts, ['codex']);
  assert.deepEqual(again.added_hosts, []);
  assert.deepEqual(again.removed, []);
});

test('dropping a host from the config and updating removes its files', (t) => {
  const root = fixture(t);
  setup(root, { hosts: ['codex', 'claude'] });
  const file = path.join(root, CONFIG_FILE);
  const config = JSON.parse(fs.readFileSync(file, 'utf8'));
  config.hosts = ['codex'];
  fs.writeFileSync(file, `${JSON.stringify(config, null, 2)}
`, 'utf8');

  const result = update(root);
  assert.deepEqual(result.hosts, ['codex']);
  assert.ok(result.removed.length > 0);
  assert.ok(result.removed.every((relative) => relative.startsWith('.claude/')));
  assert.ok(!fs.existsSync(path.join(root, '.claude', 'commands', 'castwork.md')));
  assert.ok(!fs.existsSync(path.join(root, '.claude')), 'an emptied host directory was left standing');
  assert.ok(fs.existsSync(path.join(root, '.codex', 'agents', 'worker.toml')));
});

/** What Git with core.autocrlf=true leaves on disk for a checked-out file. */
function checkOutWithCrlf(root, relative) {
  const file = path.join(root, relative);
  fs.writeFileSync(file, fs.readFileSync(file, 'utf8').replace(/\n/g, '\r\n'), 'utf8');
}

test('generated files checked out with CRLF line endings are not edits', (t) => {
  const root = fixture(t);
  const result = setup(root, { hosts: ['codex', 'claude'] });
  for (const relative of result.added) checkOutWithCrlf(root, relative);

  const updated = update(root);
  assert.deepEqual([...updated.added, ...updated.changed, ...updated.removed], []);
  const report = doctor(root);
  assert.equal(report.generated, 'current');
  assert.ok(!report.findings.some((finding) => finding.message.includes('modified locally')));
});

test('CRLF line endings do not hide a real edit', (t) => {
  const root = fixture(t);
  const result = setup(root, { hosts: ['codex'] });
  const target = result.added[0];
  fs.writeFileSync(path.join(root, target), 'edited by hand\r\n', 'utf8');
  assert.throws(() => update(root), (error) => /nothing was written/.test(error.message) && error.message.includes(target));
});

test('a dropped host whose files were checked out with CRLF is still removed', (t) => {
  const root = fixture(t);
  const result = setup(root, { hosts: ['codex', 'claude'] });
  for (const relative of result.added.filter((relative) => relative.startsWith('.claude/'))) checkOutWithCrlf(root, relative);
  const file = path.join(root, CONFIG_FILE);
  const config = JSON.parse(fs.readFileSync(file, 'utf8'));
  config.hosts = ['codex'];
  fs.writeFileSync(file, `${JSON.stringify(config, null, 2)}\n`, 'utf8');

  const updated = update(root);
  assert.ok(updated.removed.length > 0);
  assert.ok(!fs.existsSync(path.join(root, '.claude')));
});

test('remove deletes generated files checked out with CRLF', (t) => {
  const root = fixture(t);
  const result = setup(root, { hosts: ['codex'] });
  for (const relative of result.added) checkOutWithCrlf(root, relative);
  const removed = remove(root);
  assert.deepEqual(removed.kept, []);
  assert.equal(removed.removed.length, result.added.length);
});

test('validate does not report generated files checked out with CRLF', (t) => {
  const root = fixture(t);
  const result = setup(root, { hosts: ['codex'] });
  for (const relative of result.added) checkOutWithCrlf(root, relative);
  const flagged = validate(root).findings.filter((finding) => /manifest digest|out of date/.test(finding.message));
  assert.deepEqual(flagged, []);
});
